'use strict';
const el=id=>document.getElementById(id);let cases=[],selected=null;
const overview=document.createElement('section');overview.className='panel';el('collect').closest('section').before(overview);
const safety=document.createElement('details');const safetyTitle=document.createElement('summary');safetyTitle.textContent='固定安全场景集（合成，尚非真实模型成绩）';const safetyBody=document.createElement('pre');safety.append(safetyTitle,safetyBody);overview.after(safety);
async function metrics(){const m=await api('quality/metrics');overview.replaceChildren();const h=document.createElement('h2');h.textContent='质量概览 · 本机记录';overview.append(h);const rows=[['待归因',m.untriaged],['未关闭 P0',m.open_p0],['近 7 日新判定 P0 / 前 7 日',`${m.p0_triaged_last_7d} / ${m.p0_triaged_previous_7d}`],['工程回测通过 / 总次数',`${m.regression_passed} / ${m.regression_count}`],['回退决定 / 全部决定',`${m.rollback_count} / ${m.decision_count}`],['首次登记修复平均耗时',m.mean_hours_to_first_fix===null?'暂无样本':m.mean_hours_to_first_fix.toFixed(2)+' 小时（'+m.fix_sample_count+' 例）']];for(const [label,value] of rows){const p=document.createElement('p');p.textContent=label+'：'+value;overview.append(p);}const p=document.createElement('p');p.className='hint';p.textContent='零分母不显示百分比。修复时间指登记修复，并非验收完成；发布/回退是本地决定，不是云端部署。归因分布：'+Object.entries(m.causes).map(([k,v])=>k+' '+v).join(' · ');overview.append(p);}
async function api(path,body){const r=await fetch('/api/workflow/'+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-Workbench':'1'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);return d;}
function render(){selected=cases.find(c=>c.id===el('cases').value);el('detail').textContent=JSON.stringify(selected||{},null,2);for(const [id,state] of [['triage','NEW'],['fix','TRIAGED'],['decide','FIXED']])el(id).hidden=selected?.state!==state;el('command').textContent=selected?`python quality.py --db <当前服务数据库的对应路径.quality.db> --case ${selected.id}`:'';}
async function refresh(){const id=selected?.id;const d=await api('quality');cases=d.cases;el('cases').replaceChildren(...cases.map(c=>new Option(`${c.priority||'未分级'} · ${c.title} · ${c.state}`,c.id)));if(cases.some(c=>c.id===id))el('cases').value=id;el('runs').textContent=JSON.stringify({engineering:d.runs,evaluations:d.evaluations,protocols:d.protocols},null,2);render();}
async function act(fn){try{await fn();await refresh();await metrics();el('status').textContent='记录已更新';}catch(e){el('status').textContent='未完成：'+e.message;}}
el('collect').onsubmit=e=>{e.preventDefault();act(()=>api('quality/cases',Object.fromEntries(new FormData(e.target))));};
for(const action of ['triage','fix','decide'])el(action).onsubmit=e=>{e.preventDefault();if(!selected)return;const body=Object.fromEntries(new FormData(e.target));if(action==='triage')body.safety=e.target.elements.safety.checked;act(()=>api('quality/cases/'+selected.id,{...body,action,revision:selected.revision}));};
el('cases').onchange=render;el('refresh').onclick=()=>act(async()=>{});
el('freeze').onclick=()=>act(async()=>{if(!selected)throw Error('请先选择案例');const d=await api('quality/protocol',{case_id:selected.id,cases:JSON.parse(el('protocol-json').value)});el('eval-result').textContent=JSON.stringify(d,null,2);});
el('evaluate').onclick=()=>act(async()=>{if(!selected)throw Error('请先选择案例');const d=await api('quality/evaluate',{case_id:selected.id,baseline:JSON.parse(el('baseline-json').value),candidate:JSON.parse(el('candidate-json').value)});el('eval-result').textContent=JSON.stringify(d,null,2);el('decide').elements.evaluation_id.value=d.id;});
act(async()=>{await api('session',{});safetyBody.textContent=JSON.stringify(await api('quality/safety-cases'),null,2);});
