'use strict';
const $=id=>document.getElementById(id);let report=null,loading=false;
const scenarioNames={out_of_stock:'缺货',return_signed:'已签收退货',address_change:'修改地址（非当前执行MVP）',timeout:'超时'};
const errorNames={wrong_refund:'错误退款 · 建议P0复核',duplicate_execution:'重复执行 · 建议P0复核',missed_timeout:'超时遗漏 · 建议P1复核'};
const percent=n=>n===null?'—':(n*100).toFixed(1)+'%';
const num=n=>n===null?'—':Number(n).toFixed(1);
function n(tag,text){const e=document.createElement(tag);e.textContent=text;return e;}
async function api(path,body){const r=await fetch('/api/workflow/'+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-Workbench':'1'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'请求失败');return d;}
function renderRows(){const query=$('search').value.trim().toLowerCase(),scenario=$('scenario').value,flag=$('flag').value;const rows=report.rows.filter(r=>(!scenario||r.scenario===scenario)&&(!flag||(flag==='error'?r.error_flag:flag==='auto'?r.auto_closed:r.human_takeover))&&(!query||[r.ticket_id,r.order_id,r.error_type].join(' ').toLowerCase().includes(query)));$('count').textContent=`显示 ${rows.length} / ${report.rows.length} 条`;$('rows').replaceChildren();for(const r of rows){const tr=n('tr','');if(r.error_flag)tr.className='row-error';for(const v of [r.source_line,r.ticket_id,scenarioNames[r.scenario]||r.scenario,r.order_id,r.status,r.resolution,r.auto_closed?'是':'否',r.human_takeover?'是':'否',r.handling_seconds,r.receipt_verified?'是':'否',r.error_flag?'是':'否',r.error_type||'—',r.warnings.join('；')||'—'])tr.append(n('td',v));$('rows').append(tr);}}
async function load(id){if(loading)return;loading=true;$('register').disabled=true;try{
 report=await api('operations'+(id?'/'+encodeURIComponent(id):''));const d=report.dataset,m=report.metrics;
 $('dataset').replaceChildren();for(const source of report.datasets){const option=n('option',`${source.source_name} · ${source.accepted} 条 · ${source.id.slice(0,8)}`);option.value=source.id;option.selected=d?.id===source.id;$('dataset').append(option);}
 $('provenance').textContent=d?`源文件：${d.source_name}；读取 ${d.input_rows}，接纳 ${d.accepted}，隔离 ${d.rejected.length}，重复 ${d.duplicates.length}。SHA256：${d.sha256}`:'暂无数据，请先运行受控本地导入命令。';
 $('warnings').replaceChildren(...report.warnings.map(x=>n('li',x)));
 $('metrics').replaceChildren();const cards=[['模拟记录',m.total,'仅所选快照'],['自动办结标记',percent(m.auto_flag_rate),`${m.auto_flagged} / ${m.total}，不是模型准确率`],['人工接管标记',percent(m.human_takeover_rate),`${m.human_takeover} / ${m.total}`],['错误记录',m.error_count,`${percent(m.error_rate)}，以输入标记为准`],['自动且核验且无错误标记',percent(m.clean_auto_proxy_rate),`${m.clean_auto_proxy} / ${m.total}，非独立正确性验证`],['回执核验标记',percent(m.receipt_verified_rate),`${m.receipt_verified} / ${m.total}；closed中${percent(m.closed_receipt_verified_rate)}`],['平均处理秒数',num(m.mean_seconds),'是否包含等待尚未确认'],['P95处理秒数',m.p95_seconds??'—',`P50 ${m.p50_seconds??'—'} 秒；最近秩法`]];for(const [label,value,hint] of cards){const a=n('article','');a.append(n('span',label),n('strong',value),n('small',hint));$('metrics').append(a);}
 $('groups').replaceChildren();$('scenario').replaceChildren(n('option','全部'));$('scenario').firstChild.value='';for(const s of report.scenarios){const tr=n('tr','');for(const v of [scenarioNames[s.scenario]||s.scenario,s.total,`${s.auto_flagged} / ${percent(s.auto_flag_rate)}`,s.human_takeover,s.error_count,num(s.mean_seconds)])tr.append(n('td',v));$('groups').append(tr);const option=n('option',scenarioNames[s.scenario]||s.scenario);option.value=s.scenario;$('scenario').append(option);}
 $('errors').replaceChildren(...Object.entries(report.error_types).map(([kind,count])=>n('li',`${errorNames[kind]||kind}：${count} 条`)));if(!m.error_count)$('errors').append(n('li','暂无错误标记，不代表所有任务已验证正确。'));
 $('schema').textContent=JSON.stringify({mapping:d?.mapping,warning_rows:m.warning_rows,rejected:d?.rejected||[],duplicates:d?.duplicates||[],auto_only_mean_seconds:m.auto_only_mean_seconds,human_only_mean_seconds:m.human_only_mean_seconds},null,2);
 $('registration').textContent='';renderRows();$('notice').textContent='已载入模拟快照。与任务执行、真实模型评测和真实经营效果隔离。';
}catch(e){$('notice').textContent='读取失败：'+e.message;}finally{loading=false;$('register').disabled=!report?.dataset||!report.metrics.error_count;}}
$('dataset').onchange=()=>load($('dataset').value);$('scenario').onchange=renderRows;$('flag').onchange=renderRows;$('search').oninput=renderRows;
$('register').onclick=async()=>{if(!report?.dataset)return;$('register').disabled=true;try{const r=await api('operations/register-errors',{dataset_id:report.dataset.id});$('registration').textContent=`已关联 ${r.count} 条待复核案例（重复点击不会重复建案）。请前往质量工作台进行归因。`;}catch(e){$('registration').textContent='登记失败：'+e.message;}finally{$('register').disabled=false;}};
api('session',{}).then(()=>load()).catch(e=>{$('notice').textContent='连接失败：'+e.message;});
