const scenarios=[
 {id:'delay',icon:'⇢',name:'物流停滞',risk:'低风险',riskClass:'',subtitle:'轨迹停滞 72h，用户尚未投诉',order:'OD-829104',customer:'周凯 · 高价值',signal:'杭州中转仓 · 72h 无更新',budget:'自动授权 ≤ ¥35',plans:[['催促原包裹','48h','¥0','62%'],['附近仓重发','24h','¥18','94%'],['原路退款','1–3 天','¥329','100%']],selected:1,result:'已从上海仓重新发货',resultText:'新单 OD-829104-R 已出库；原包裹设置拒收。系统已主动通知客户，无需创建工单。',verification:['新单揽收','已确认'],steps:[['检测异常','事件监控发现物流轨迹超过 SLA 24 小时','monitor_shipment','stalled_72h'],['读取上下文','查询订单、客户价值、收货时限和历史售后','get_order_context','vip · gift_deadline'],['生成方案','比较催件、重发与退款的解决概率和成本','plan_recovery','3_candidates'],['执行补救','锁定附近仓库存并创建替换订单','create_replacement','OD-829104-R'],['通知客户','解释异常与解决方案，提供改选退款入口','notify_customer','delivered'],['验证解决','检测新单揽收，并在签收后回访满意度','verify_outcome','resolved']]},
 {id:'damage',icon:'◇',name:'商品破损',risk:'中风险',riskClass:'medium',subtitle:'图片质检 96% 确认为运输破损',order:'OD-829236',customer:'许安然 · 普通',signal:'客户上传 3 张破损照片',budget:'客户确认后自动执行',plans:[['全额退款','1–3 天','¥168','100%'],['免费补发','24h','¥14','92%'],['补偿券','即时','¥30','41%']],selected:1,result:'客户确认后已完成补发',resultText:'Agent 发送两种方案，客户选择免费补发；替换订单已创建并通过仓库质检。',verification:['客户选择','补发完成'],steps:[['检测异常','视觉质检识别杯体破损并匹配订单','inspect_evidence','damage_0.96'],['读取上下文','核验订单、库存、历史退款与产品政策','get_order_context','eligible'],['生成方案','按体验、成本和成功率生成三种补救方案','plan_recovery','3_candidates'],['询问客户','主动提供退款或免费补发选择','ask_customer','replacement'],['执行补救','创建补发单并标记出库前二次质检','create_replacement','OD-829236-R'],['验证解决','新包裹签收，回访未出现重复投诉','verify_outcome','resolved']]},
 {id:'payment',icon:'¥',name:'重复扣款',risk:'低风险',riskClass:'',subtitle:'支付回调检测到同订单双重扣款',order:'OD-829411',customer:'沈妍 · 新客',signal:'相同幂等键出现 2 笔支付',budget:'重复支付可自动退款',plans:[['退回重复款','秒级发起','¥0','99%'],['转为储值余额','即时','¥0','68%'],['创建人工工单','4h','¥12','100%']],selected:0,result:'重复款已原路退回',resultText:'退款 RF-60192 已受理；Agent 将持续监听支付状态，到账后才计为解决。',verification:['退款受理','到账待验'],steps:[['检测异常','支付回调发现同一幂等键发生重复扣款','detect_duplicate','2_charges'],['读取上下文','比对支付渠道、金额、订单和风控状态','get_payment_context','confirmed'],['选择策略','匹配重复支付政策并检查自动退款权限','authorize_refund','within_policy'],['执行退款','向原支付渠道发起重复款退款','create_refund','RF-60192'],['通知客户','主动告知退款金额、路径与预计到账时间','notify_customer','delivered'],['验证解决','监听支付网关到账回调，异常则自动重试','verify_refund','monitoring']]},
 {id:'stock',icon:'□',name:'缺货冲突',risk:'中风险',riskClass:'medium',subtitle:'付款后库存同步失败，无法按期出库',order:'OD-829508',customer:'顾然 · 会员',signal:'库存锁定失败 · SKU-7012',budget:'价差补贴 ≤ ¥50',plans:[['升级替代款','24h','¥36','89%'],['等待补货','5 天','¥0','52%'],['全额退款','1–3 天','¥459','100%']],selected:0,result:'已免费升级替代商品',resultText:'客户接受同系列升级款；Agent 自动补贴 ¥36 价差并更新订单，无需退款重购。',verification:['客户接受','已出库'],steps:[['检测异常','库存服务返回锁定失败，预测将违反出库 SLA','monitor_inventory','lock_failed'],['读取上下文','查找同类库存、价格差和客户偏好','find_alternatives','4_matches'],['生成方案','比较升级替代、等待补货和退款','plan_recovery','3_candidates'],['询问客户','展示可次日发货的升级款并免除价差','ask_customer','upgrade'],['执行变更','替换 SKU、应用补贴并重新锁定库存','update_order','success'],['验证解决','升级商品已出库且预计准时送达','verify_outcome','resolved']]},
 {id:'injury',icon:'!',name:'安全事件',risk:'高风险',riskClass:'high',subtitle:'破损商品导致划伤，触发安全红线',order:'OD-829620',customer:'陈雨桐 · VIP',signal:'对话中识别“划伤、流血”',budget:'强制人工审批',plans:[['退款 + 医疗补助','立即','待审批','—'],['仅全额退款','1–3 天','¥268','低'],['普通补发','24h','¥18','不适用']],selected:0,result:'安全处置方案已执行',resultText:'主管批准后，Agent 继续完成退款、医疗补助、客户关怀和同批次商品排查。',verification:['主管批准','处置完成'],steps:[['检测异常','从客户对话识别人身伤害与产品安全风险','classify_safety','critical'],['读取上下文','保全对话、图片、批次与订单证据','preserve_evidence','complete'],['生成方案','依据安全政策生成处置与关怀方案','plan_safety_response','ready'],['权限检查','金额与风险超过自治权限，必须暂停','check_authority','approval_required'],['执行补救','执行退款、医疗补助与批次排查','execute_package','success'],['验证解决','跟踪客户状况并确认同批次是否存在风险','verify_safety','resolved']]}
];
let current=scenarios[0],running=false,stepIndex=-1,runTimer=null,modelReady=false,liveDecision=null;
const $=s=>document.querySelector(s);
function renderScenarios(){
  $('#scenarioList').innerHTML=scenarios.map(s=>`<button class="scenario ${s.id===current.id?'active':''}" data-id="${s.id}"><div class="scenario-top"><span class="scenario-icon">${s.icon}</span><strong>${s.name}</strong><i class="risk-chip ${s.riskClass}">${s.risk}</i></div><p>${s.subtitle}</p></button>`).join('');
  document.querySelectorAll('.scenario').forEach(b=>b.onclick=()=>selectScenario(b.dataset.id));
}
function selectScenario(id){if(running)return;current=scenarios.find(s=>s.id===id);resetRun(false);renderScenarios();renderCase()}
function renderCase(){
  $('#caseTitle').textContent=`${current.name} · ${current.subtitle.split('，')[0]}`;
  $('#caseContext').innerHTML=`<div class="context-item"><span>订单</span><strong>${current.order}</strong></div><div class="context-item"><span>客户</span><strong>${current.customer}</strong></div><div class="context-item"><span>触发信号</span><strong>${current.signal}</strong></div>`;
  if(stepIndex<0){$('#timeline').innerHTML=`<div class="empty-run"><div><div class="empty-visual">✦</div><strong>准备运行闭环演练</strong><p>Agent 将读取实时事件，自主规划并调用业务工具。选择左侧场景后点击“运行 Agent”。</p></div></div>`;$('#decisionContent').innerHTML=`<div class="decision-placeholder"><div><span>◎</span>运行后显示授权范围、候选方案、执行结果与验证状态。</div></div>`;return}
  $('#timeline').innerHTML=current.steps.map((s,i)=>`<div class="step ${i<stepIndex?'done':i===stepIndex?'active':''}"><span class="step-dot">${i<stepIndex?'✓':i+1}</span><div class="step-card"><div class="step-head"><strong>${s[0]}</strong><time>${i<stepIndex?'完成':i===stepIndex?'执行中':'等待'}</time></div><p>${s[1]}</p><span class="tool-call"><b>TOOL</b> ${s[2]} → ${i<=stepIndex?s[3]:'—'}</span></div></div>`).join('');
  renderDecision();
}
function renderDecision(){
  const high=current.riskClass==='high',finished=stepIndex>=current.steps.length;
  $('#decisionContent').innerHTML=`<section class="decision-block"><h3>动态授权</h3><div class="authority"><div class="authority-ring"><strong>${high?'L1':'L3'}</strong></div><div><strong>${current.risk}</strong><span>${current.budget}</span></div></div><div class="rule" style="margin-top:11px">${high?'命中安全红线：Agent 可完成调查和方案设计，但不得自行执行资金与安全处置。':'未命中安全红线：Agent 可在预算和政策范围内自主执行，并保留审计记录。'}</div></section><section class="decision-block"><h3>方案比较</h3><div class="plan">${current.plans.map((p,i)=>`<div class="plan-row ${i===current.selected?'selected':''}"><span>${i===current.selected?'✓':i+1}</span><div><strong>${p[0]}</strong><small>${p[1]} · 成本 ${p[2]}</small></div><em>${p[3]}</em></div>`).join('')}</div></section>${high&&stepIndex===3?`<section class="decision-block"><div class="approval"><strong>需要安全主管决策</strong><p>Agent 已完成证据整理和方案设计。批准后将从暂停点继续执行。</p><div class="approval-actions"><button class="reject" id="rejectBtn">转人工处理</button><button class="approve" id="approveBtn">批准并继续</button></div></div></section>`:''}${finished?`<section class="decision-block"><h3>结果验证</h3><div class="result-card"><span class="result-label">${high?'APPROVED RECOVERY':'VERIFIED RESOLUTION'}</span><strong>${current.result}</strong><p>${current.resultText}</p><div class="verify">${current.verification.map(v=>`<span>${v}<b>✓</b></span>`).join('')}</div></div></section>`:''}`;
  if(liveDecision){$('#decisionContent').insertAdjacentHTML('afterbegin',`<section class="decision-block"><h3>DeepSeek 实时判断</h3><div class="model-decision"><span>${liveDecision.risk_level} · ${liveDecision.needs_human?'需要人工':'可自动执行'}</span><p>${liveDecision.summary}</p><p><strong>建议：</strong>${liveDecision.recommended_action} · 置信度 ${Math.round(liveDecision.confidence*100)}%</p></div></section>`)}
  if($('#approveBtn'))$('#approveBtn').onclick=approveHighRisk;
  if($('#rejectBtn'))$('#rejectBtn').onclick=()=>{stopRun();$('#runBtn').disabled=true;setStatus('paused','已转人工');showToast('已携带完整上下文转交安全专员')};
}
function setStatus(type,text){$('#runStatus').className=`run-status ${type}`;$('#runStatus').innerHTML=`<i></i>${text}`}
async function startRun(){if(running)return;resetRun(false);running=true;$('#runBtn').disabled=true;setStatus('running',modelReady?'DeepSeek 判断中':'Agent 运行中');if(modelReady){try{liveDecision=await requestDecision({scenarioId:current.id,eventText:current.subtitle,context:{order:current.order,customer:current.customer,signal:current.signal,budget:current.budget}})}catch(e){liveDecision=null;showToast('模型暂时不可用，已安全降级为评测沙盘')}}if(!running)return;setStatus('running','Agent 运行中');advance()}
function advance(){stepIndex++;renderCase();if(current.riskClass==='high'&&stepIndex===3){running=false;$('#runBtn').disabled=true;setStatus('paused','等待审批');return}if(stepIndex>=current.steps.length){finishRun();return}runTimer=setTimeout(advance,720)}
function approveHighRisk(){running=true;showToast('审批通过，Agent 从暂停点继续执行');setStatus('running','继续执行');stepIndex++;renderCase();runTimer=setTimeout(advance,720)}
function finishRun(){running=false;$('#runBtn').disabled=true;setStatus('complete',current.riskClass==='high'?'处置已执行':'已验证解决');showToast(current.riskClass==='high'?'高风险方案已批准并执行':'问题已闭环解决，结果写入评测样本')}
function stopRun(){running=false;clearTimeout(runTimer);$('#runBtn').disabled=false}
function resetRun(notify=true){stopRun();stepIndex=-1;liveDecision=null;setStatus('idle','等待运行');renderCase();if(notify)showToast('演练已重置')}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
async function requestDecision(payload){const response=await fetch('/api/agent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error||'模型请求失败');return data.decision}
async function checkModel(){try{const r=await fetch('/api/health');const data=await r.json();modelReady=Boolean(data.configured);$('#modelChip').textContent=modelReady?'DeepSeek 实时推理':'DeepSeek 接口已预留';$('#modelChip').className=`demo-chip ${modelReady?'live':'fallback'}`;$('#runtimeNote').innerHTML=modelReady?'<span>●</span> DeepSeek 负责语义理解与决策建议；后端规则负责权限校验和工具执行。':'<span>●</span> 当前使用确定性评测沙盘；DeepSeek 服务端接口与 Prompt 位置已经预留，但未配置密钥、不会产生费用。'}catch(e){modelReady=false;$('#modelChip').textContent='DeepSeek 接口已预留';$('#modelChip').className='demo-chip fallback'}}
async function analyzeCustom(){const text=$('#customInput').value.trim();if(!text)return;$('#analyzeBtn').disabled=true;$('#customStatus').textContent='DeepSeek 正在分析…';$('#customResult').hidden=true;try{const d=await requestDecision({scenarioId:'custom',eventText:text,context:{source:'sandbox_demo'}});$('#customResult').textContent=JSON.stringify(d,null,2);$('#customResult').hidden=false;$('#customStatus').textContent='分析完成'}catch(e){$('#customStatus').textContent=modelReady?'调用失败，请稍后再试':'接口演示位：未配置 API Key'}finally{$('#analyzeBtn').disabled=false}}
$('#runBtn').onclick=startRun;$('#resetBtn').onclick=()=>resetRun(true);$('#customBtn').onclick=()=>$('#customDialog').showModal();$('#analyzeBtn').onclick=analyzeCustom;$('#evalBtn').onclick=()=>$('#evalDialog').showModal();$('#designBtn').onclick=()=>$('#designDialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());renderScenarios();renderCase();checkModel();
if(document.modelContext?.registerTool){Promise.resolve(document.modelContext.registerTool({name:'run_recovery_scenario',title:'运行售后自愈演练',description:'选择一个订单异常场景并启动 Agent 闭环演练。',inputSchema:{type:'object',properties:{scenarioId:{type:'string',enum:scenarios.map(s=>s.id)}},required:['scenarioId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const found=scenarios.find(s=>s.id===input?.scenarioId);if(!found)throw new Error('未知场景');if(running)throw new Error('已有演练正在运行');current=found;renderScenarios();renderCase();startRun();return{scenarioId:found.id,risk:found.risk,status:'started',authorization:found.budget}}})).catch(()=>{})}
