'use strict';
const $ = id => document.getElementById(id);
const states = {READY:'待执行',WAITING_HUMAN:'等待人工',RETRYABLE:'等待重试 / 对账',COMPLETED:'已核验完成'};
const events = {'event.received':'接收缺货事件','context.loaded':'读取业务事实','planner.completed':'完成方案规划','planner.failed':'规划失败','guardrail.blocked':'安全校验拦截','human.requested':'请求人工核对','human.confirmed':'人工确认已记录','tool.executed':'沙箱工具已执行','tool.response_lost':'模拟响应丢失','execution.reconciled':'回执对账','result.verified':'核验业务结果'};
let current=null, connected=false, busy=false;
function notice(message,error=false){$('notice').textContent=message;$('notice').classList.toggle('error',error);}
function element(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
async function api(path,body){const response=await fetch('/api/workflow/'+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-Workbench':'1'},body:body===undefined?undefined:JSON.stringify(body)});let result;try{result=await response.json();}catch{throw new Error('当前网页没有可用的工作流后端。');}if(response.status===401){$('signIn').hidden=location.hostname==='127.0.0.1';throw new Error('请先登录。任务按登录身份隔离，不允许匿名写入。');}if(!response.ok)throw new Error(result.error||'接口请求失败');return result;}
function controls(){for(const id of ['create','refresh','scenario'])$(id).disabled=!connected||busy;$('run').disabled=busy||!current||!['READY','RETRYABLE'].includes(current.state);for(const e of $('confirmForm').elements)e.disabled=busy;document.querySelectorAll('.taskbutton').forEach(b=>b.disabled=busy);$('download').disabled=busy||!current;}
async function action(fn){if(busy)return;busy=true;controls();try{await fn();}catch(e){notice('操作未完成：'+e.message+'。已填写的确认内容会保留，请刷新任务核对状态后再试。',true);}finally{busy=false;controls();}}
async function loadList(){const data=await api('tasks');const list=data.tasks;$('total').textContent=list.length;$('completed').textContent=list.filter(t=>t.state==='COMPLETED').length;$('human').textContent=list.filter(t=>t.state==='WAITING_HUMAN').length;$('retryable').textContent=list.filter(t=>t.state==='RETRYABLE').length;$('tasks').replaceChildren();if(!list.length)$('tasks').append(element('p','暂无任务，选择场景开始。','muted'));for(const t of list){const b=element('button',undefined,'taskbutton'+(current?.id===t.id?' active':''));b.append(element('strong',states[t.state]||t.state),element('span',t.order_id),element('span',new Date(t.created_at).toLocaleString()));b.onclick=()=>action(async()=>{render(await api('tasks/'+t.id));await loadList();});$('tasks').append(b);}return list;}
function render(task){current=task;$('empty').hidden=true;$('taskBody').hidden=false;$('taskTitle').textContent=task.order_id.split('-')[0]==='conflict'?'客户意愿冲突':task.order_id.startsWith('tool_failure')?'执行响应丢失':'售后处置任务';$('taskState').textContent=states[task.state]||task.state;$('taskMeta').textContent='Task '+task.id+' · 已尝试 '+task.attempts+' 次';const f=task.order.facts;$('quote').textContent=f.customer_text;$('source').textContent='原始消息 '+f.message_id+' · '+new Date(f.message_at).toLocaleString();$('factGrid').replaceChildren();for(const [label,value]of [['结构化偏好',f.accept_substitute?'接受替代品':'不接受替代品'],['有效确认意愿',f.confirmed_intent==='replace'?'换货':f.confirmed_intent==='refund'?'退款':'未确认'],['替代品库存',f.stock],['实付 / 替代品价格',`¥${(f.paid_minor/100).toFixed(2)} / ¥${(f.price_minor/100).toFixed(2)}`],['人工确认记录',f.human_confirmed?'已有':'暂无'],['订单业务状态',task.order.status]]){const cell=element('div');cell.append(element('span',label),element('strong',String(value)));$('factGrid').append(cell);}$('confirmForm').hidden=task.state!=='WAITING_HUMAN';$('confirmForm').reset();$('run').textContent=task.state==='RETRYABLE'?'查询回执并重试':'执行任务';$('runHint').textContent=task.state==='COMPLETED'?'已完成核验，不允许重复执行。':task.state==='WAITING_HUMAN'?'先确认需求，保存后可继续执行。':task.state==='RETRYABLE'?'执行可能已经成功；后端将优先查询回执。':'只操作沙箱数据，不触达真实客户。';$('outcome').replaceChildren();if(task.plan){$('outcome').append(element('strong','建议：'+({replace:'换货',refund:'退款',human:'转人工'}[task.plan.action]||task.plan.action)),element('p',task.plan.reason));}if(task.receipt){$('outcome').append(element('p',`回执 ${task.receipt.id} · ${task.receipt.status} · ${task.receipt.sandbox?'沙箱':'未知环境'}`));}$('trace').replaceChildren();for(const row of task.trace){const li=element('li');li.append(element('strong',events[row.event]||row.event),element('time',new Date(row.at).toLocaleString()));const d=element('details');d.append(element('summary','查看结构化证据'),element('pre',JSON.stringify(row.details,null,2)));li.append(d);$('trace').append(li);}controls();}
$('create').onclick=()=>action(async()=>{render(await api('demo',{scenario:$('scenario').value}));await loadList();notice('新演练任务已保存。点击“执行任务”开始。');});
$('refresh').onclick=()=>action(async()=>{await loadList();if(current)render(await api('tasks/'+current.id));notice('已从后端刷新任务状态。');});
$('run').onclick=()=>action(async()=>{notice('正在处理，请等待后端返回结果…');render(await api('tasks/'+current.id+'/run',{}));await loadList();notice('后端返回：'+states[current.state]+'。');});
$('confirmForm').onsubmit=e=>{e.preventDefault();if(!$('confirmForm').reportValidity())return;const payload={intent:$('intent').value,source_message_id:current.order.facts.message_id,note:$('note').value.trim()};action(async()=>{render(await api('tasks/'+current.id+'/confirm',payload));await loadList();notice('人工确认已保存；点击“执行任务”恢复处理。');});};
$('download').onclick=()=>{if(!current)return;const url=URL.createObjectURL(new Blob([JSON.stringify(current,null,2)],{type:'application/json'}));const a=element('a');a.href=url;a.download='hengzhun-task-'+current.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('evidenceToggle').onclick=()=>{$('evidence').hidden=!$('evidence').hidden;if(!$('evidence').hidden)$('evidence').scrollIntoView({behavior:'smooth',block:'start'});};
async function init(){try{await api('session',{});const health=await api('health');connected=true;$('connection').textContent=health.environment==='cloud-sandbox'?'云端后端已连接':'本机后端已连接';$('planner').textContent='规划器：'+health.planner+(health.planner.startsWith('rule')?'（确定性替身，不调用模型）':'（真实模型，调用可能计费）');const list=await loadList();if(list.length)render(await api('tasks/'+list[0].id));notice('已连接持久化后端。所有任务为合成演练，当前指标来自已载入任务。');}catch(e){$('connection').textContent='后端未连接';notice(e.message,true);}finally{controls();}}init();
